Fix traceback in release helper
The get_old_stabilization_branch returns a list. The function
remove_old_stabilization_branch needs 2 arguments.

Addressing:
[jcerny@fedora utils{stabilization-v0.1.68}]$ ./release_helper.py -c ~/secret.ini -r ComplianceAsCode/content cleanup --branch
Traceback (most recent call last):
  File "/home/jcerny/work/git/scap-security-guide/utils/./release_helper.py", line 780, in <module>
    main()
  File "/home/jcerny/work/git/scap-security-guide/utils/./release_helper.py", line 776, in main
    subcmds[args.subcmd](repo, args)
  File "/home/jcerny/work/git/scap-security-guide/utils/./release_helper.py", line 638, in cleanup
    remove_old_stabilization_branch(branch_to_remove)
TypeError: remove_old_stabilization_branch() missing 1 required positional argument: 'branch'