Stop using "imp" module
Fixes broken build on Fedora Rawhide.

The deprecated importlib API has been removed from Python 3.12,
see https://github.com/python/cpython/issues/98040.

Addressing:

Traceback (most recent call last):
  File "/builddir/build/BUILD/scap-security-guide-0.1.69/build-scripts/build_templated_content.py", line 9, in <module>
    import ssg.templates
  File "/builddir/build/BUILD/scap-security-guide-0.1.69/ssg/templates.py", line 5, in <module>
    import imp
ModuleNotFoundError: No module named 'imp'