tests/install_vm.py: add timeouted wait for VM to shutdown
Added timeout should prevent issues where a VM is still in
the `running` state after `virsh console` disconnects and
therefore subsequent `virsh start` fails, e.g.:

```
Starting Reboot...

dracut Warning: Killing all remaining processes
Rebooting.
[  522.430163] reboot: Restarting system

error: Domain is already active
```