Fix traceback in SSGTS when packages can't be installed.
The string was being constructed with { package } and it was being
interpreted by the format python function as if it was a keyword to be
replaced by a string in the error_msg_template.format function.

```
  File "tests/ssg_test_suite/common.py", line 654, in install_packages
    test_env.execute_ssh_command(
  File "tests/ssg_test_suite/test_env.py", line 133, in execute_ssh_command
    error_msg = error_msg_template.format(
KeyError: "'ntp', 'chrony'"
```