python3 support for ansible roles builder [1/2]
{}.iteritems() is no longer available in python 3.x. Instead, we can use just
{}.items() to maintain compatibility with python2 and python3 alike, while
making python2 version marginally theoretically academically less efficient.

Addressing:
Converting Ansible Playbook ./ansible/rhel8-playbook-ospp.yml to Ansible Role ./ansible_roles/rhel8_ospp
Traceback (most recent call last):
  File "../utils/ansible_playbook_to_role.py", line 519, in <module>
    main()
  File "../utils/ansible_playbook_to_role.py", line 482, in main
    PlaybookToRoleConverter(playbook_full_path).save_to_disk(args.dry_run)
  File "../utils/ansible_playbook_to_role.py", line 312, in save_to_disk
    open(abs_path, 'w').write(self.file(filename).encode("utf-8"))
  File "../utils/ansible_playbook_to_role.py", line 269, in file
    return self._generate_defaults_content()
  File "../utils/ansible_playbook_to_role.py", line 297, in _generate_defaults_content
    default_vars_local_content = yaml.dump(self.default_vars_data, width=120, indent=4,
  File "/usr/lib64/python3.8/site-packages/yaml/__init__.py", line 290, in dump
    return dump_all([data], stream, Dumper=Dumper, **kwds)
  File "/usr/lib64/python3.8/site-packages/yaml/__init__.py", line 278, in dump_all
    dumper.represent(data)
  File "/usr/lib64/python3.8/site-packages/yaml/representer.py", line 27, in represent
    node = self.represent_data(data)
  File "/usr/lib64/python3.8/site-packages/yaml/representer.py", line 48, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "../utils/ansible_playbook_to_role.py", line 46, in dict_representer
    return dumper.represent_mapping(_mapping_tag, data.iteritems())
AttributeError: 'collections.OrderedDict' object has no attribute 'iteritems'