bugfix: ssg/xml: drop duplicate definition of get_test_action_ref_element
From pyflakes:
ssg/xml.py:431:5: redefinition of unused 'get_test_action_ref_element' from line 427